# Generated by Django 4.1.7 on 2023-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspots',
            name='best_tide',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surfspots',
            name='break_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surfspots',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surfspots',
            name='sea_bed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surfspots',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
