# Generated by Django 4.1.7 on 2023-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_surfspots_best_tide_surfspots_break_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspots',
            name='youtube_id',
            field=models.CharField(default='j_U4niuqUhg', max_length=100),
        ),
    ]
