# Generated by Django 4.1.7 on 2023-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_surfspots_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspots',
            name='levels',
            field=models.CharField(blank=True, choices=[('BtP', 'Beginner Pro'), ('ItP', 'Intermediate Pro'), ('AtP', 'Advanced Pro'), ('P', 'Pro')], max_length=3),
        ),
    ]
